# Generated by Django 2.2.17 on 2020-12-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='candidate_Id',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='lastName',
        ),
        migrations.AddField(
            model_name='politician',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
