# Generated by Django 2.2.17 on 2020-12-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0002_auto_20201204_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='name',
            field=models.CharField(default='XXXXX XXXXXX', max_length=200),
        ),
    ]
