# Generated by Django 2.2.17 on 2020-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0002_politician_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='party',
            field=models.CharField(default='none', max_length=5, null=True),
        ),
    ]
