# Generated by Django 2.2.17 on 2020-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Organization_Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Politician_Name', max_length=200)),
                ('party', models.CharField(default='none', max_length=5, null=True)),
                ('candidate_id', models.TextField(null=True)),
            ],
        ),
    ]
