# Generated by Django 2.2.17 on 2020-12-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
